version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "part:tooling"
      - "type:tech-debt"
    versioning-strategy: auto
    open-pull-requests-limit: 10
    groups:
      required:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      optional:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    ignore:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "part:tooling"
      - "type:tech-debt"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "friday"
    labels:
      - "part:tooling"
      - "type:tech-debt"
    versioning-strategy: auto
    open-pull-requests-limit: 10
    groups:
      required:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      optional:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
