[package]
name = "frequenz-resampling"
version = "0.1.0"
edition = "2021"

[lib]
name = "frequenz_resampling"
crate-type = ["rlib"]

[features]

[dependencies]
itertools = "0.13"
num-traits = "0.2"
chrono = "0.4"
log = "0.4"
