[package]
name = "frequenz-resampling"
version = "0.3.0"
edition = "2021"
description = "A library for resampling a stream of samples to a given interval."
repository = "https://github.com/frequenz-floss/frequenz-resampling-rs"
license = "MIT"

[lib]
name = "frequenz_resampling"

[dependencies]
itertools = "0.15"
num-traits = "0.2"
chrono = "0.4"
log = "0.4"
