name: Python Test

on:
  merge_group:
  pull_request:
  push:
    tags:
      - '*'
    branches-ignore:
      - 'gh-readonly-queue/**'
      - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
        nox-session:
          - "pytest_min"
        python:
          - "3.11"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run nox
        uses: frequenz-floss/gh-action-nox@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          nox-session: ${{ matrix.nox-session }}
          git-username: ${{ secrets.GIT_USER }}
          git-password: ${{ secrets.GIT_PASS }}
