name: Rust Test

on:
  merge_group:
  pull_request:
  push:
    tags:
      - '*'
    branches-ignore:
      - 'gh-readonly-queue/**'
      - 'dependabot/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run tests
        uses: frequenz-floss/gh-action-cargo-test@v1.0.0
